In [8]:
import pandas as pd
import numpy as np
import csv
import sys

reviewfile = "/Users/skhederian/restaurant-health/the_final_countdown.csv"
csv.field_size_limit(sys.maxsize)
df = pd.read_csv(reviewfile, sep=",", encoding = 'utf-8', engine = 'python')
df.head(100)

_id          restaurant_name  \
0   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
1   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
2   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
3   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
4   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
5   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
6   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
7   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
8   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
9   ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
10  ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
11  ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
12  ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
13  ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
14  ObjectId(581151a5b6729e7e313481a0)                 131 MAIN   
15  ObjectId(5830680cf3f071f6de30b48f)  163 Vietnamese Sandwich   
16  ObjectId(5830680cf3f071f6de30b48f)  163 Vietnamese Sandwich   
17  ObjectId(5830680cf3f071f6de30b48f)  163 Vietnamese Sandwich   
18  ObjectId(5830680cf3f071f6de30b48f)  163 Vietnamese Sandwich   
19  ObjectId(5830680cf3f071f6de30b48f)  163 Vietnamese Sandwich   
20  ObjectId(5830680cf3f071f6de30b48f)  163 Vietnamese Sandwich   
21  ObjectId(581151a8b6729e7e31355077)              1897 MARKET   
22  ObjectId(581151a8b6729e7e31355077)              1897 MARKET   
23  ObjectId(581151a8b6729e7e31355077)              1897 MARKET   
24  ObjectId(581151a8b6729e7e31355077)              1897 MARKET   
25  ObjectId(581151a8b6729e7e31355077)              1897 MARKET   
26  ObjectId(581151a7b6729e7e31351889)       1900 ASIAN CUISINE   
27  ObjectId(581151a7b6729e7e31351889)       1900 ASIAN CUISINE   
28  ObjectId(581151a7b6729e7e31351889)       1900 ASIAN CUISINE   
29  ObjectId(581151a7b6729e7e31351889)       1900 ASIAN CUISINE   
..                                 ...                      ...   
70  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
71  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
72  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
73  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
74  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
75  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
76  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
77  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
78  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
79  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
80  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
81  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
82  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
83  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
84  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
85  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
86  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
87  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
88  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
89  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
90  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
91  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
92  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
93  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
94  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
95  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
96  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
97  ObjectId(5830680cf3f071f6de30b431)        224 BOSTON STREET   
98  ObjectId(58

In [10]:
#scaled with mean zero
from sklearn import preprocessing
X = np.array(df[['review_count', 'stars', 'violations', 'pricerange', 'PreviousViolations', 'DiffPreviousTwo']])

In [11]:
X_scaled = preprocessing.scale(X)

In [12]:
X_scaled

array([[ 0.47068601,  0.53588951,  0.34934962,  0.85559539, -0.81865411,
         0.03426208],
       [ 0.47068601,  0.53588951, -0.01599034,  0.85559539,  0.3977954 ,
         0.03426208],
       [ 0.47068601,  0.53588951, -0.13777032,  0.85559539,  0.03286054,
        -0.34658076],
       ..., 
       [-0.63517597,  1.94939932, -0.38133029,  0.85559539, -0.45371926,
         0.1612097 ],
       [-0.63517597,  1.94939932, -0.25955031,  0.85559539, -0.33207431,
         0.1612097 ],
       [-0.63517597,  1.94939932, -0.01599034,  0.85559539, -0.21042936,
         0.1612097 ]])

In [15]:
#scaled with range 0-1
X_train = np.array(df[['review_count', 'stars', 'violations', 'pricerange', 'PreviousViolations', 'DiffPreviousTwo']])
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax

array([[ 0.10734758,  0.75      ,  0.1       ,  0.5       ,  0.        ,
         0.5       ],
       [ 0.10734758,  0.75      ,  0.07      ,  0.5       ,  0.1       ,
         0.5       ],
       [ 0.10734758,  0.75      ,  0.06      ,  0.5       ,  0.07      ,
         0.485     ],
       ..., 
       [ 0.00260552,  1.        ,  0.04      ,  0.5       ,  0.03      ,
         0.505     ],
       [ 0.00260552,  1.        ,  0.05      ,  0.5       ,  0.04      ,
         0.505     ],
       [ 0.00260552,  1.        ,  0.07      ,  0.5       ,  0.05      ,
         0.505     ]])

In [16]:
#Normalization (scaling individual samples to have unit norm)
X_normalized = np.array(df[['review_count', 'stars', 'violations', 'pricerange', 'PreviousViolations', 'DiffPreviousTwo']])
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[ 0.99862923,  0.01911252,  0.0477813 ,  0.00955626,  0.        ,
         0.        ],
       [ 0.99807112,  0.01910184,  0.03342822,  0.00955092,  0.0477546 ,
         0.        ],
       [ 0.99869763,  0.01911383,  0.02867075,  0.00955692,  0.0334492 ,
        -0.01433537],
       ..., 
       [ 0.7333588 ,  0.45834925,  0.3666794 ,  0.1833397 ,  0.27500955,
         0.09166985],
       [ 0.68853037,  0.43033148,  0.43033148,  0.17213259,  0.34426519,
         0.0860663 ],
       [ 0.6172134 ,  0.38575837,  0.54006172,  0.15430335,  0.38575837,
         0.07715167]])